### ISSUE TITLE
What is «Auto align number column to right»?

### ISSUE THREAD

**Issue by Kristinita** [vkocubinsky/SublimeTableEditor#56]
Hello, I don't understand how functions «[Auto align number column to right](https://github.com/vkocubinsky/SublimeTableEditor#auto-align-number-column-to-right)». I add in my `.sublime-settings ` file line `"table_editor_align_number_right": true`, but numbers not align to right.<br />
1. If hlines are absent, numbers remain in the same position where I wrote them.

![Without hlines](http://i.imgur.com/InGPMks.gif)<br />
2. If hlines is, numbers are aligned to the center, but not to the right.

![With hlines](http://i.imgur.com/kWzsCJa.gif)

All options except this correctly work for me. @vkocubinsky, would you add illustrations to be able to understand the functioning of this option?

### Environment

* Operating system and version:  
   * Windows 10 Education
* Sublime Text:
  * Build 3114

Thanks.

**Comment by vkocubinsky** [comment]
Hi , I moved to vim and doesn't have installed sublime and doesn't support this package. Probably SublimeTableEditor doesn't supported your case as on a picture. But if I remember correctly Sublime Table Editor try to recognise is data has only numbers and if yes and if table_editor_align_number_right is true align number to right. I guess before hline is header , header aligned to center, you can try tables like this

```
|    Name   | Age |
|-----------|-----|
| Anna      |  20 |
| Alexander |  27 |
```

I expected column Age will be aligned to right.

Also as a workaround you can specify alignment
```
| column 1 | column 2 | column 3 |
| <<<<<<<< | >>>>>>>> | ######## |
|----------|----------|----------|
| 1        |    row 1 |    c1    |
| 2        |    row 2 |    c2    |
| 3        |    row 3 |    c3    |
```

**Comment by Kristinita** [comment]
#59
