### ISSUE TITLE
In Sublime Text 3, when I click ctrl + shift + p, sublime's package control opens

### ISSUE THREAD

**Issue by LuckyMona** [vkocubinsky/SublimeTableEditor#58]
How I handle this, so that I can use table editor in sublime text 3?  Sorry for my poor English.

**Comment by vkocubinsky** [comment]
Hi,

This package is no more supported. But it worked in sublime text 3. I don't know what is the current status. When you click control+shift+p you can enable sublime table editor. But before you have to install it as described in Installation section.

Thanks!

**Comment by LuckyMona** [comment]
Hi,

Thanks very much for your answer! In my condition, Ctrl + shift + p is the shortcut key of opening package control, it is conflict with the shortcut key of table editor. The sublime shortcut key setting profile  is readonly, so I tried to change the shortcut key of table editor in this path: Package Settings -> Table Editor -> Key Bindings - default, but I can't find ctrl + shift +p, Is there a method to change the  Ctrl + shift + p to other key group?

**Comment by vkocubinsky** [comment]
I am afraid I am not clear understand you,  ctrl+shift+p is not table editor shortcut, it is sublime shortcut for launch command palette , see http://docs.sublimetext.info/en/latest/extensibility/command_palette.html. Command palette should be available(it looks it is true for you, but you can also enable table editor manually with customise table editor properties). 
Package control https://packagecontrol.io/docs/usage can be launched from command palette. Also from command palette you can install and enable Table Editor. 

I would suggest you try to followup the instruction https://github.com/vkocubinsky/SublimeTableEditor/blob/master/README.md, you have to look on Installation section and Settings section these 2 should contains answer on your questions.

**Comment by LuckyMona** [comment]
Thanks very much！
