### ISSUE TITLE
Insert new empty cell (and not new row)

### ISSUE THREAD

**Issue by josephernest** [vkocubinsky/SublimeTableEditor#61]
Using `SHIFT+ALT+DOWN` creates a whole new row, i.e. an empty cell is added *for each column*.
How to add a new cell **for the current column only**?

Before (current cell: hello)

```
    | A   | B      | C      |
    | sqd | hello  | world  |
    |     | qsdqsd | sqdqsd |
    |     |        |        |
```

After:

```
    | A   | B      | C      |
    | sqd |        | world  |
    |     | hello  | sqdqsd |
    |     | qsdqsd |        |
```

A cell has been inserted before `hello`. Columns A and C are not modified.

**Comment by vkocubinsky** [comment]
I guess this functionality is not provided by sublime table editor, probably Sublime Editor can work with rectangular areas and you can try use this as a workaround.

**Comment by josephernest** [comment]
Thanks for your answer @vkocubinsky .

> I guess this functionality is not provided by sublime table editor

I could try to add this feature. Would you have a few hints : where in TableEditor's code to put this? how to select the current cell only (and not current row), with a regexp?


> probably Sublime Editor can work with rectangular areas and you can try use this as a workaround.

Which plugin are you talking about? Thanks in advance.

**Comment by josephernest** [comment]
Working version here: https://github.com/josephernest/SublimeTableEditor
