### ISSUE TITLE
How to proceed with the "unmaintained" state?

### ISSUE THREAD

**Issue by robinrosenstock** [vkocubinsky/SublimeTableEditor#65]
@vkocubinsky:

I don't like the note: "This package is no more supported. I moved to vim.", I would like to remove it.
I want to collaborate a bit, so can you [make me a collaborator](https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/)?
Or maybe you want to [transfer the repository](https://help.github.com/articles/about-repository-transfers/) to another user?
But you still accept Pull requests, don't you?

**Comment by vkocubinsky** [comment]
I don't not accept pull request, and I have no installed Sublime to check does it work. I guess you can fork repository , rename it to something like SublimeTableEditor2 or any other, post message to sublime forum that you support this plugin. And in case if somebody make an issue or pull request I can redirect  it to your repository.

**Comment by robinrosenstock** [comment]
Well, I would like to hold on to the current name, because than it's easier to find.
Why not transfer the repository to me? [Here is the guidance](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/). This is the easiest possibility, and no work for you with redirecting anything after that.

**Comment by robinrosenstock** [comment]
But when you hold on to your stars on Github and everything, I just fork it, of course.

**Comment by vkocubinsky** [comment]
I would like keep it as is. Anybody can fork and make his own version and publish with new name.

**Comment by robinrosenstock** [comment]
@vkocubinsky:
Can you make me a collaborator at least, in order that I can clone the Issues from your repo into [mine](https://github.com/geniusupgrader/SublimeTableEditor) more easier? Otherwise I will remade them by hand.

**Comment by robinrosenstock** [comment]
@vkocubinsky:
How to proceed with packagecontrol?
Can I update the repository to mine?
Or do you really want that I change the name to SublimeTableEditor2? But then there will be a `SublimeTableEditor` and a `SublimeTableEditor2` in packagecontrol.

**Comment by robinrosenstock** [comment]
[My Fork](https://github.com/geniusupgrader/SublimeTableEditor)
